### ISSUE TITLE
Compile, Install error

### ISSUE THREAD

**Issue by zoidy34** [naworkcaj/bdvl#1]
_Sorry for my english._
Platform: Ubuntu 16.04 minimal: Linux ubuntu 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Compile with suggested -dbc gave me this error:
`fatal error: pcap/pcap.h: No such file or directory`
After installed dependencies with -D, full install -i gave this error 
`bdvl.c:28:31: fatal error: security/pam_appl.h: No such file or directory`

**Comment by naworkcaj** [comment]
The package, on Debian, libpam0g-dev needs to be installed.
Will put in a quick edit so I can close this.
:smile:
