### ISSUE TITLE
Continuous test feedback results information

### ISSUE THREAD

**Issue by hackendltd** [naworkcaj/bdvl#10]
os:centos7 newest x86_64
./bedevil.sh -ti
 [!] Patch dynamic linker libs? [Y/n]: y [..] Patching dynamic linker libraries, please wait...
etc/patch_libdl.sh: line 38: /root/bdvl/etc/get_rand_path.sh: No such file or directory
etc/patch_libdl.sh: line 38: random: command not found

**Comment by naworkcaj** [comment]
Appreciated. :+1:
