### ISSUE TITLE
Breaks a lot of things

### ISSUE THREAD

**Issue by trollByte** [naworkcaj/bdvl#2]
I can no longer SSH as a valid user.  I can not connect to the backdoor via PAM or SSH.  Here are the details of my machine below. 

Any assistance would be appreciated. 

 [..] Decide what you want to enable/disable.
 [+] USE_ACCEPT_BD = false. Switch? [Y/n]: 
 [+] USE_PAM_BD = false. Switch? [Y/n]: 
 [+] LOG_LOCAL_AUTH = false. Switch? [Y/n]: 
 [+] LOG_SSH = false. Switch? [Y/n]: 
 [+] FILE_STEAL = false. Switch? [Y/n]: 
 [+] ACCEPT_USE_SSL = false. Switch? [Y/n]: n
 [+] Starting full installation!

 [!] Patch dynamic linker libs? [Y/n]: n
 [!] Install potential dependencies? [Y/n]: 
 [..] Installing dependencies

Linux ubuntu 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 49
model name      : AMD Ryzen Threadripper 3970X 32-Core Processor
stepping        : 0
microcode       : 0x8301025
cpu MHz         : 4150.004
cache size      : 512 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec clzero arat overflow_recov succor
bugs            : fxsave_leak sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 8300.00
TLB size        : 3072 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

 [+] Finished installing dependencies

 [..] Building & writing C char arrays for the lib headers
 [..] Writing background variables
 [..] Getting hidden port ranges
 [..] Overwriting variable placeholders with new settings

 [..] BD_UNAME = xtuklcx
 [..] BD_PWD = ppenkpu
 [..] MAGIC_GID = 3498
 [..] ACCEPT_PORT = 442
 [..] PAM_PORT = 445

In file included from libeaseyp.so.inc/hooks/libdl/libdl.h:37:0,
                 from libeaseyp.so.inc/includes.h:13,
                 from libeaseyp.so.inc/bedevil.c:4:
libeaseyp.so.inc/util/xor_wrappers.h: In function ‘xprintf’:
libeaseyp.so.inc/util/xor_wrappers.h:24:18: warning: format not a string literal and no format arguments [-Wformat-security]
     ret = printf(str);
                  ^
In file included from libeaseyp.so.inc/hooks/libdl/../../util/util.h:13:0,
                 from libeaseyp.so.inc/hooks/libdl/dladdr.c:1,
                 from libeaseyp.so.inc/hooks/libdl/libdl.h:41,
                 from libeaseyp.so.inc/includes.h:13,
                 from libeaseyp.so.inc/bedevil.c:4:
libeaseyp.so.inc/hooks/libdl/../../util/processes.c: In function ‘get_process_name’:
libeaseyp.so.inc/hooks/libdl/../../util/processes.c:16:9: warning: format not a string literal and no format arguments [-Wformat-security]
         (void)snprintf(process_name, 5, bstr);
         ^
libeaseyp.so.inc/hooks/libdl/../../util/processes.c:16:9: warning: format not a string literal and no format arguments [-Wformat-security]
libeaseyp.so.inc/hooks/libdl/../../util/processes.c: In function ‘get_process_cmdline’:
libeaseyp.so.inc/hooks/libdl/../../util/processes.c:61:9: warning: format not a string literal and no format arguments [-Wformat-security]
         (void)snprintf(process_cmdline, 5, bstr);
         ^
libeaseyp.so.inc/hooks/libdl/../../util/processes.c:61:9: warning: format not a string literal and no format arguments [-Wformat-security]
 [+] Rootkit compiled. (libeaseyp.so.x86_64 - 73K)
 [+] Rootkit compiled. (libeaseyp.so.i686 - 75K)
 [..] Installing to /usr/lib/sasl2/.26336
 [..] Writing $SOPATH to /etc/ld.so.preload
 [+] Installation finished
 [+] Cleaning up local mess

 [..] Hiding rootkit files
 [+] Installation complete

**Comment by naworkcaj** [comment]
Thanks for this. Will have a look and push an update soon.

**Comment by naworkcaj** [comment]
Due to the new & existing issue #3 I am going to close this and pin the newer issue. Work is being done on this to fix existing issues.
If you should have anything to add to this post, please add it in the newer & pinned issue, referencing anything that may need it.
Thanks again! ❤️
