### ISSUE TITLE
program execution cannot proceed to the next step and is in a suspended state

### ISSUE THREAD

**Issue by hackendltd** [naworkcaj/bdvl#5]
os version: CentOS Linux release 7.7.1908 (Core)

[root@pth bdvl]# ./bedevil.sh -ti

   ___                    ___                             ___  
  (   )                  (   )                      .-.  (   ) 
   | |.-.     .--.     .-.| |    .--.    ___  ___  ( __)  | |  
   | /   \   /    \   /   \ |   /    \  (   )(   ) (''")  | |  
   |  .-. | |  .-. ; |  .-. |  |  .-. ;  | |  | |   | |   | |  
   | |  | | |  | | | | |  | |  |  | | |  | |  | |   | |   | |  
   | |  | | |  |/  | | |  | |  |  |/  |  | |  | |   | |   | |  
   | |  | | |  ' _.' | |  | |  |  ' _.'  | |  | |   | |   | |  
   | '  | | |  .'.-. | '  | |  |  .'.-.  ' '  ; '   | |   | |  
   ' `-' ;  '  `-' / ' `-'  /  '  `-' /   \ `' /    | |   | |  
    `.__.    `.__.'   `.__,'    `.__.'     '_.'    (___) (___) 
                                                             
                                                             
 [..] Beginning toggle configuration...
 [!] USE_ACCEPT_BD = false. Switch? [Y/n]: y
 [!] USE_PAM_BD = false. Switch? [Y/n]: y
 [!] LOG_LOCAL_AUTH = false. Switch? [Y/n]: y
 [!] LOG_SSH = false. Switch? [Y/n]: y
 [!] FILE_STEAL = false. Switch? [Y/n]: y
 [!] ACCEPT_USE_SSL = false. Switch? [Y/n]: y
 [+] Starting full installation!

 [!] Patch dynamic linker libs? [Y/n]: y [..] Patching dynamic linker libraries

#no next step...

if
 [..] Beginning toggle configuration...
 [!] USE_ACCEPT_BD = false. Switch? [Y/n]: y
 [!] USE_PAM_BD = false. Switch? [Y/n]: y
 [!] LOG_LOCAL_AUTH = false. Switch? [Y/n]: y
 [!] LOG_SSH = false. Switch? [Y/n]: y
 [!] FILE_STEAL = false. Switch? [Y/n]: y
 [!] ACCEPT_USE_SSL = false. Switch? [Y/n]: y
 [+] Starting full installation!

 [!] Patch dynamic linker libs? [Y/n]: n
 [!] Install potential dependencies? [Y/n]: n
 [..] Building & writing C char arrays for the lib headers
 [..] Writing background variables
 [..] Getting hidden ports
 [..] Getting variable placeholders and their new values
#no next step...

I waited a long time and forced to quit.

**Comment by naworkcaj** [comment]
Problems addressed above have been resolved as of the most recent commits to the repository. Thanks.
